version: '3.9'
services:
  bank-app:
    build:
      context: .
    ports:
      - "5000:5000" 
    env_file:
      - .env 
    depends_on:
      - postgres
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    command: npm run dev 

  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vrRwzrfgmlNpyhNHJYbRnsopSXwAswuU
      POSTGRES_DB: railway
    ports:
      - "20708:20708"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
